blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/', views.CreateView.as_view(), name='create'),
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('selfPublished/', views.FilterAuthorView.as_view(), name='selfPub'),
    path('orderDate/', views.OrderDateView.as_view(), name='orderDate'),
    path('today/', views.TodayView.as_view(), name='todayDate'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls')),
]

blogs/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blogs/views.py
from django.shortcuts import render
from django.urls.base import set_urlconf
from django.views import generic
from .models import Post
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .filters import PostFilter
from django.utils import timezone

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'blogs/index.html'
    context_object_name = 'blogs_list'

    def get_queryset(self):
        """Return all the blogs."""
        return Post.objects.all()

class SearchView(generic.ListView):
    template_name = 'blogs/search.html'
    context_object_name = 'blogs_list'

    def get_queryset(self):
        """Return all the blogs."""
        return Post.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        return context

class CreateView(generic.edit.CreateView):
    template_name = 'blogs/create.html'
    model = Post
    fields = ['text', 'title', 'author']
    success_url = reverse_lazy('blogs:index')

class UpdateView(generic.edit.UpdateView):
    template_name = 'blogs/update.html'
    model = Post
    fields = ['text', 'title']
    success_url = reverse_lazy('blogs:index')

class DeleteView(generic.edit.DeleteView):
    template_name = 'blogs/delete.html' # override default of greetings/greeting_confirm_delete.html
    model = Post
    success_url = reverse_lazy('blogs:index')

# Filtered Pages
class FilterAuthorView(generic.ListView):
    template_name = 'blogs/filauthor.html'
    context_object_name = 'blogs_list'

    def get_queryset(self):
        """Return all the blogs."""
        me = User.objects.get(username=self.request.user)
        return Post.objects.filter(author=me)

class OrderDateView(generic.ListView):
    template_name = 'blogs/orddate.html'
    context_object_name = 'blogs_list'

    def get_queryset(self):
        """Return all the blogs."""
        return Post.objects.order_by('-published_date')


class TodayView(generic.ListView):
    template_name = 'blogs/today.html'
    context_object_name = 'blogs_list'

    def get_queryset(self):
        """Return all the blogs."""
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')

blogs/templates/blogs/create.html
{% load static %}
<link rel="stylesheet" type = "text/css" href="{% static 'blogs/styles.css' %}">
<a href="{% url 'blogs:index' %}">Teleport back to SPACE</a>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

blogs/templates/blogs/delete.html
<a href="{% url 'blogs:index' %}">HOME</a>
<form method="post">{% csrf_token %}
    <p>Are you sure? This will be gone forever "{{ object.text }}"?</p>
    <input type="submit" value="Confirm">
</form>

blogs/templates/blogs/filauthor.html
{% load static %}
<link rel="stylesheet" type = "text/css" href="{% static 'blogs/styles.css' %}">

<h1>YOU MADE THESE!!1 </h1>
<a href="{% url 'blogs:index' %}"> Teleport back to SPACE </a>
{% if blogs_list %}
        <ul>
        <h2> Hello {{user.username}}!</h2>
        
        {% for blog in blogs_list %}
            <li>
                <h4>{{ blog.title }}<br></h4>
                Text: {{ blog.text }} <br>
                Written by: {{ blog.author }} <br>
                Published on: {{ blog.published_date }} <br>
                <span><a href="{% url 'blogs:update' blog.id %}">edit</a></span>
                <span><a href="{% url 'blogs:delete' blog.id %}">delete</a></span><br>
            </li>
        {% endfor %}
        </ul>

{% else %}
    <p>You need to write more</p>
{% endif %}

blogs/templates/blogs/index.html
{% load static %}

<link rel="stylesheet" type = "text/css" href="{% static 'blogs/styles.css' %}">
<h1>Welcome to the Groovy Space Blog</h1>
{% if blogs_list %}
        <ul>
            <h2> Greetings {{user.username}}!</h2>
            <div>
                <a href="{% url 'blogs:create' %}">Make a New Post</a> <br> <br>
                <a href="{% url 'blogs:selfPub' %}">Your posts</a> <br> <br>
                <a href="{% url 'blogs:orderDate' %}">Newest to Oldest</a> <br> <br>
                <a href="{% url 'blogs:todayDate' %}">Posts made today</a> <br> <br>
                <a href="{% url 'blogs:search' %}">Looking for something?</a> <br>
            </div>
        <br><br>
        <h2>The kool kats are talkin</h2>
        {% for blog in blogs_list %}
            <li>
                <h4>{{ blog.title }}<br></h4>
                Text: {{ blog.text }} <br> <br>
                Written by: {{ blog.author }} <br>
                Published on: {{ blog.published_date }} <br>
                <span><a href="{% url 'blogs:update' blog.id %}">edit</a></span>
                <span><a href="{% url 'blogs:delete' blog.id %}">delete</a></span>
            </li>
            <p> {{blog.author}}: <span style = "color:blue">{{user.username}}</span></p>
            {% if blog.author == user %}
                <p> --You wrote this article</p>
            {% endif %}
        {% endfor %}
        </ul>

{% else %}
    <p>we are out in space now</p>
{% endif %}

blogs/templates/blogs/orddate.html
{% load static %}
<link rel="stylesheet" type = "text/css" href="{% static 'blogs/styles.css' %}">

<h1>Newest to Oldest Posts</h1>
<a href="{% url 'blogs:index' %}">Teleport back to SPACE </a>
{% if blogs_list %}
        <ul>        
        {% for blog in blogs_list %}
            <li>
                <h4>{{ blog.title }}<br></h4>
                Text: {{ blog.text }} <br>
                Written by: {{ blog.author }} <br>
                Published on: {{ blog.published_date }} <br>
                <span><a href="{% url 'blogs:update' blog.id %}">edit</a></span>
                <span><a href="{% url 'blogs:delete' blog.id %}">delete</a></span>
            </li>
        {% endfor %}
        </ul>

{% else %}
    <p>No posts exist</p>
{% endif %}

blogs/templates/blogs/search.html
{% load static %}
<link rel="stylesheet" type = "text/css" href="{% static 'blogs/styles.css' %}">

<h1>GROOVY SPACE BLOG</h1>
<a href="{% url 'blogs:index' %}">Teleport back to SPACE </a>
{% if blogs_list %}
        <ul>
        <h3>What would you like to find?</h3>
        <br>
        <form method="GET">
            {{ filter.form }}
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
        

        {% for blog in filter.qs %}
            <li>
                <h4>{{ blog.title }}<br></h4>
                Text: {{ blog.text }} <br>
                Written by: {{ blog.author }} <br>
                Published on: {{ blog.published_date }} <br>
                <span><a href="{% url 'blogs:update' blog.id %}">edit</a></span>
                <span><a href="{% url 'blogs:delete' blog.id %}">delete</a></span><br>
            </li>
        {% endfor %}
        </ul>

{% else %}
    <p>You need to write more</p>
{% endif %}

blogs/templates/blogs/today.html
{% load static %}
<link rel="stylesheet" type = "text/css" href="{% static 'blogs/styles.css' %}">

<h1>Posts Created Today</h1>
<a href="{% url 'blogs:index' %}">Teleport back to SPACE </a>
{% if blogs_list %}
        <ul>        
        {% for blog in blogs_list %}
            <li>
                <h4>{{ blog.title }}<br></h4>
                Text: {{ blog.text }} <br>
                Written by: {{ blog.author }} <br>
                Published on: {{ blog.published_date }} <br>
                <span><a href="{% url 'blogs:update' blog.id %}">edit</a></span>
                <span><a href="{% url 'blogs:delete' blog.id %}">delete</a></span><br>
            </li>
        {% endfor %}
        </ul>

{% else %}
    <p>Nothing but space here</p>
{% endif %}

blogs/templates/blogs/update.html
<a href="{% url 'blogs:index' %}">HOME</a>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    <a href="{% url 'blogs:delete' post.id %}">delete</a>
</form>